// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PD4ExamAPI.Models;

#nullable disable

namespace PD4ExamAPI.Migrations
{
    [DbContext(typeof(MazeGameContext))]
    [Migration("20250606154202_AddedFKToMazeTile")]
    partial class AddedFKToMazeTile
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PD4ExamAPI.Models.Maze", b =>
                {
                    b.Property<int>("MazeId")
                        .HasColumnType("int")
                        .HasColumnName("MazeID");

                    b.Property<DateOnly>("CreationDate")
                        .HasColumnType("date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("MazeId");

                    b.ToTable("Maze", (string)null);
                });

            modelBuilder.Entity("PD4ExamAPI.Models.MazeTile", b =>
                {
                    b.Property<int>("TileId")
                        .HasColumnType("int")
                        .HasColumnName("TileID");

                    b.Property<int>("ColumnIndex")
                        .HasColumnType("int");

                    b.Property<int>("MazeId")
                        .HasColumnType("int");

                    b.Property<int>("RowIndex")
                        .HasColumnType("int");

                    b.Property<string>("TileType")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.HasKey("TileId");

                    b.HasIndex("MazeId");

                    b.ToTable("MazeTile", (string)null);
                });

            modelBuilder.Entity("PD4ExamAPI.Models.Player", b =>
                {
                    b.Property<int>("PlayerId")
                        .HasColumnType("int")
                        .HasColumnName("PlayerID");

                    b.Property<DateOnly>("CreationDate")
                        .HasColumnType("date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("PlayerId");

                    b.ToTable("Player", (string)null);
                });

            modelBuilder.Entity("PD4ExamAPI.Models.MazeTile", b =>
                {
                    b.HasOne("PD4ExamAPI.Models.Maze", "Maze")
                        .WithMany()
                        .HasForeignKey("MazeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Maze");
                });
#pragma warning restore 612, 618
        }
    }
}
